# Generated by Django 5.2.7 on 2025-11-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano_lancamento', models.DateField()),
                ('autor', models.CharField(max_length=50)),
                ('quant_paginas', models.IntegerField()),
                ('disponiveis', models.IntegerField()),
            ],
        ),
    ]
