# Generated by Django 5.2.7 on 2025-11-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano_lancamento',
            field=models.IntegerField(),
        ),
    ]
